# Generated by Django 2.2 on 2019-09-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
